import { useEffect, useRef, useState } from 'react'
import { Bot, ChevronDown, Eraser, Send, Sparkles, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { financeTips, productivityTips, quotes } from '../../data/knowledge'
import { monthTransactions, useChatbotStore, useFinanceStore, usePersonalStore, useSettingsStore } from '../../store'
import { currencyFormatOptions } from '../../utils/formatting'
import { formatCurrency } from '../../utils/helpers'
import { IconButton } from '../ui'

const suggestions=['Où en est mon budget ?','Que dois-je prioriser ?','Donne-moi une motivation','Analyse mon épargne']
function createAnswer(input:string){
  const q=input.toLowerCase(), finance=useFinanceStore.getState(), personal=usePersonalStore.getState(), settings=useSettingsStore.getState(), monthly=monthTransactions(finance.transactions)
  const income=monthly.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0), expenses=monthly.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0), balance=income-expenses
  const money=(v:number)=>formatCurrency(v,settings.currency,settings.hideAmounts,currencyFormatOptions(settings))
  if(/budget|dépense|depense|solde|finance/.test(q)){const top=finance.budgets.map(b=>({name:b.category,spent:monthly.filter(t=>t.type==='expense'&&t.category===b.category).reduce((s,t)=>s+t.amount,0),planned:b.planned})).sort((a,b)=>b.spent/a.planned-a.spent/b.planned)[0];return `Ce mois-ci, vous avez reçu ${money(income)} et dépensé ${money(expenses)}, soit un solde de ${money(balance)}. ${top?`${top.name} est la catégorie la plus avancée (${Math.round(top.spent/top.planned*100)} %).`:''} Conseil : ${financeTips[(new Date().getDate()+q.length)%financeTips.length]}`}
  if(/épargne|epargne|objectif financier|econom/.test(q)){const saved=finance.savingsGoals.reduce((s,g)=>s+g.current,0), target=finance.savingsGoals.reduce((s,g)=>s+g.target,0);return `Vos objectifs d’épargne totalisent ${money(saved)} sur ${money(target)}, soit ${Math.round(saved/target*100)} %. Continuez les versements réguliers : la constance compte plus que le timing parfait.`}
  if(/tâche|tache|prior|productiv|faire|aujourd/.test(q)){const open=personal.tasks.filter(t=>t.status!=='done'), urgent=open.filter(t=>t.priority==='urgent'||t.priority==='high');return `Vous avez ${open.length} tâches actives, dont ${urgent.length} à priorité haute. Commencez par « ${urgent[0]?.title??open[0]?.title??'une courte revue de vos objectifs'} ». ${productivityTips[(new Date().getDate()+q.length)%productivityTips.length]}`}
  if(/objectif|progress|goal/.test(q)){const goal=[...personal.goals].sort((a,b)=>a.progress-b.progress)[0];return goal?`L’objectif qui mérite le plus d’attention est « ${goal.title} », actuellement à ${goal.progress} %. Identifiez aujourd’hui une action de moins de 20 minutes pour relancer son élan.`:'Ajoutez un objectif SMART et je pourrai suivre sa progression avec vous.'}
  if(/motivation|inspir|courage|citation/.test(q))return `« ${quotes[(new Date().getDate()+q.length)%quotes.length]} » Votre prochain pas n’a pas besoin d’être grand, seulement clair.`
  if(/bonjour|salut|hello/.test(q))return `Bonjour ${settings.profile.name.split(' ')[0]} ! Je vois ${personal.tasks.filter(t=>t.status!=='done').length} tâches actives et un solde mensuel de ${money(balance)}. Sur quoi voulez-vous avancer ?`
  return `Je peux analyser vos finances, prioriser vos tâches, suivre vos objectifs et vous aider à garder le cap. ${productivityTips[(q.length+new Date().getMinutes())%productivityTips.length]}`
}

export function Chatbot(){
  const open=useChatbotStore(s=>s.isOpen),setOpen=useChatbotStore(s=>s.setOpen),messages=useChatbotStore(s=>s.messages),addMessage=useChatbotStore(s=>s.addMessage),clear=useChatbotStore(s=>s.clear),typing=useChatbotStore(s=>s.isTyping),setTyping=useChatbotStore(s=>s.setTyping),[text,setText]=useState(''),end=useRef<HTMLDivElement>(null)
  useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,typing,open])
  const send=(value=text)=>{const clean=value.trim();if(!clean||typing)return;addMessage({role:'user',content:clean});setText('');setTyping(true);window.setTimeout(()=>{addMessage({role:'assistant',content:createAnswer(clean)});setTyping(false)},650+Math.min(clean.length*12,800))}
  return <><AnimatePresence>{open&&<motion.aside className="chat-panel" role="dialog" aria-label="Assistant LifeOS" initial={{opacity:0,y:20,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:15,scale:.97}}><header><span className="assistant-avatar"><Sparkles size={19}/></span><span><b>Assistant LifeOS</b><small><i/>Local & contextuel</small></span><IconButton label="Effacer l’historique" onClick={()=>confirm('Effacer cette conversation ?')&&clear()}><Eraser size={17}/></IconButton><IconButton label="Fermer l’assistant" onClick={()=>setOpen(false)}><X size={18}/></IconButton></header><div className="chat-messages">{messages.map(m=><div key={m.id} className={`chat-message ${m.role}`}><span>{m.role==='assistant'&&<Bot size={15}/>}</span><p>{m.content}</p></div>)}{typing&&<div className="chat-message assistant"><span><Bot size={15}/></span><p className="typing-dots"><i/><i/><i/></p></div>}<div ref={end}/></div>{messages.length<3&&<div className="chat-suggestions">{suggestions.map(s=><button key={s} onClick={()=>send(s)}>{s}</button>)}</div>}<form className="chat-input" onSubmit={(e)=>{e.preventDefault();send()}}><textarea rows={1} value={text} onChange={(e)=>setText(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Posez une question sur votre LifeOS…"/><button aria-label="Envoyer" disabled={!text.trim()||typing}><Send size={17}/></button></form><footer>Vos données restent dans ce navigateur.</footer></motion.aside>}</AnimatePresence><button className={`chat-launcher ${open?'open':''}`} onClick={()=>setOpen(!open)} aria-label={open?'Réduire l’assistant':'Ouvrir l’assistant'}>{open?<ChevronDown/>:<><Sparkles/><span><b>Besoin d’aide ?</b><small>Parlez à votre assistant</small></span></>}</button></>
}
