import { useRef, useState } from 'react'
import { Bell, Check, Database, Download, Eye, EyeOff, FileSpreadsheet, Gift, Keyboard, LayoutGrid, LockKeyhole, Palette, Save, Shield, Trash2, Upload, User, WalletCards } from 'lucide-react'
import { motion } from 'framer-motion'
import { modules } from '../../data/modules'
import { useDashboardStore, useFinanceStore, usePersonalStore, useSettingsStore, useUIStore } from '../../store'
import type { Density, Settings, Theme } from '../../types'
import { downloadFile, initials } from '../../utils/helpers'
import { Badge, Button, Input, Select, Toggle } from '../ui'

const sections = [
  { id: 'profile', label: 'Profil', icon: User }, { id: 'appearance', label: 'Apparence', icon: Palette }, { id: 'locale', label: 'Langue & région', icon: WalletCards },
  { id: 'dashboard', label: 'Dashboard', icon: LayoutGrid }, { id: 'notifications', label: 'Notifications', icon: Bell }, { id: 'data', label: 'Données', icon: Database },
  { id: 'security', label: 'Sécurité', icon: Shield }, { id: 'shortcuts', label: 'Raccourcis', icon: Keyboard },
]
export function SettingsPage() {
  const [section,setSection]=useState('profile')
  return <motion.div className="page settings-page" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div className="page-heading"><div><span className="eyebrow">PERSONNALISATION</span><h1>Paramètres</h1><p>LifeOS s’adapte à votre rythme, vos préférences et votre façon de travailler.</p></div><Badge tone="free"><Gift size={12}/> TOUT INCLUS</Badge></div><div className="settings-shell"><nav className="settings-nav">{sections.map((item)=><button key={item.id} className={section===item.id?'active':''} onClick={()=>setSection(item.id)}><item.icon size={17}/>{item.label}</button>)}</nav><div className="settings-content"><SettingsSection id={section}/></div></div></motion.div>
}

function SettingsSection({id}:{id:string}){
  const state=useSettingsStore(), update=useSettingsStore((s)=>s.update), updateProfile=useSettingsStore((s)=>s.updateProfile), showToast=useUIStore((s)=>s.showToast), fileRef=useRef<HTMLInputElement>(null)
  const save=()=>showToast('Paramètres enregistrés automatiquement')
  if(id==='profile') return <SettingsBlock title="Votre profil" description="Ces informations personnalisent les salutations et l’assistant."><div className="profile-editor"><div className="avatar-upload"><span className="avatar xlarge">{state.profile.avatar?<img src={state.profile.avatar} alt="Avatar"/>:initials(state.profile.name)}</span><div><Button variant="secondary" size="sm" onClick={()=>fileRef.current?.click()}><Upload size={15}/>Changer la photo</Button><small>JPG ou PNG, stocké localement.</small></div><input ref={fileRef} hidden type="file" accept="image/*" onChange={(e)=>{const file=e.target.files?.[0];if(file){const reader=new FileReader();reader.onload=()=>updateProfile({avatar:String(reader.result)});reader.readAsDataURL(file)}}}/></div><div className="form-grid"><Field label="Nom complet"><Input value={state.profile.name} onChange={(e)=>updateProfile({name:e.target.value})}/></Field><Field label="Email"><Input type="email" value={state.profile.email} onChange={(e)=>updateProfile({email:e.target.value})}/></Field><Field label="Téléphone"><Input value={state.profile.phone} onChange={(e)=>updateProfile({phone:e.target.value})}/></Field><Field label="Ville"><Input value={state.profile.city} onChange={(e)=>updateProfile({city:e.target.value})}/></Field><Field label="Date de naissance"><Input type="date" value={state.profile.birthDate} onChange={(e)=>updateProfile({birthDate:e.target.value})}/></Field><Field label="Bio" wide><textarea className="input" rows={3} value={state.profile.bio} onChange={(e)=>updateProfile({bio:e.target.value})}/></Field></div><Button onClick={save}><Save size={16}/>Enregistrer</Button></div></SettingsBlock>
  if(id==='appearance') return <SettingsBlock title="Apparence" description="Choisissez une ambiance cohérente avec votre espace."><SettingGroup title="Thème"><ChoiceCards options={[{id:'light',label:'Clair',hint:'Toujours lumineux'},{id:'dark',label:'Sombre',hint:'Confort le soir'},{id:'auto',label:'Automatique',hint:'Selon le système'}]} value={state.theme} onChange={(v)=>update({theme:v as Theme})}/></SettingGroup><SettingGroup title="Couleur d’accent"><div className="accent-options">{(['smoke','sage','slate','terracotta'] as const).map((accent)=><button key={accent} className={`${accent} ${state.accent===accent?'active':''}`} onClick={()=>update({accent})}><i/><span>{accent==='smoke'?'Fumée':accent==='sage'?'Sauge':accent==='slate'?'Ardoise':'Terre cuite'}</span>{state.accent===accent&&<Check size={15}/>}</button>)}</div></SettingGroup><SettingGroup title="Densité"><ChoiceCards options={[{id:'compact',label:'Compacte',hint:'Plus d’informations'},{id:'comfortable',label:'Confortable',hint:'Équilibrée'},{id:'spacious',label:'Spacieuse',hint:'Plus aérée'}]} value={state.density} onChange={(v)=>update({density:v as Density})}/></SettingGroup><SettingGroup title="Mouvements"><ToggleRow label="Animations d’interface" text="Transitions et révélations fluides" value={state.animations} onChange={(v)=>update({animations:v})}/><ToggleRow label="Effet fumée" text="Brume douce en arrière-plan" value={state.smoke} onChange={(v)=>update({smoke:v})}/><ToggleRow label="Parallax subtil" text="Profondeur de la bannière" value={state.parallax} onChange={(v)=>update({parallax:v})}/></SettingGroup></SettingsBlock>
  if(id==='locale') return <SettingsBlock title="Langue & région" description="Formats utilisés dans tout le dashboard."><div className="form-grid"><Field label="Langue"><Select value={state.language} onChange={(e)=>update({language:e.target.value as Settings['language']})}><option value="fr">🇫🇷 Français</option><option value="en">🇬🇧 English</option></Select></Field><Field label="Devise"><Select value={state.currency} onChange={(e)=>update({currency:e.target.value as Settings['currency']})}>{['MAD','EUR','USD','GBP','CAD','CHF','AED'].map((x)=><option key={x}>{x}</option>)}</Select></Field><Field label="Format de date"><Select value={state.dateFormat} onChange={(e)=>update({dateFormat:e.target.value as Settings['dateFormat']})}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></Select></Field><Field label="Format de l’heure"><Select value={state.timeFormat} onChange={(e)=>update({timeFormat:e.target.value as Settings['timeFormat']})}><option value="24h">24 heures</option><option value="12h">12 heures</option></Select></Field><Field label="Fuseau horaire" wide><Select value={state.timezone} onChange={(e)=>update({timezone:e.target.value})}>{['Africa/Casablanca','Europe/Paris','Europe/London','America/New_York','Asia/Dubai','Asia/Tokyo'].map((x)=><option key={x}>{x}</option>)}</Select></Field></div></SettingsBlock>
  if(id==='dashboard') return <DashboardSettings/>
  if(id==='notifications') return <SettingsBlock title="Notifications & coach" description="Contrôlez les alertes utiles sans bruit inutile."><ToggleRow label="Notifications LifeOS" text="Interrupteur principal" value={state.notifications} onChange={(v)=>update({notifications:v})}/><ToggleRow label="Alertes de budget" text="À 80 % et en cas de dépassement" value={state.budgetAlerts} onChange={(v)=>update({budgetAlerts:v})}/><ToggleRow label="Coach proactif" text="Conseils contextuels selon vos données" value={state.coachMode} onChange={(v)=>update({coachMode:v})}/><div className="form-grid top-space"><Field label="Fréquence du coach"><Select value={state.coachFrequency} onChange={(e)=>update({coachFrequency:e.target.value as Settings['coachFrequency']})}><option value="never">Jamais</option><option value="daily">Quotidien</option><option value="weekly">Hebdomadaire</option></Select></Field></div></SettingsBlock>
  if(id==='data') return <DataSettings/>
  if(id==='security') return <SettingsBlock title="Sécurité locale" description="Protection sur cet appareil, sans transfert de données."><div className="form-grid"><Field label="PIN à 4 chiffres"><Input type="password" inputMode="numeric" maxLength={4} value={state.pin} onChange={(e)=>/^\d{0,4}$/.test(e.target.value)&&update({pin:e.target.value})}/></Field></div><ToggleRow label="Masquer les montants" text="Remplace tous les chiffres financiers par •••••" value={state.hideAmounts} onChange={(v)=>update({hideAmounts:v})} icon={state.hideAmounts?<EyeOff/>:<Eye/>}/><ToggleRow label="Verrouiller le journal" text="Demande le PIN avant la lecture" value={state.journalLocked} onChange={(v)=>update({journalLocked:v})}/><div className="security-note"><LockKeyhole size={18}/><span><b>Protection locale</b>Ce PIN améliore la confidentialité sur un appareil partagé mais ne remplace pas le chiffrement du système.</span></div></SettingsBlock>
  return <SettingsBlock title="Raccourcis clavier" description="Naviguez plus vite dans LifeOS."><div className="shortcuts-list">{[['⌘ K','Recherche globale'],['⌘ T','Nouvelle tâche'],['⌘ N','Nouvelle note'],['⌘ M','Nouvelle transaction'],['⌘ /','Ouvrir l’assistant'],['⌘ ⇧ L','Changer de thème'],['⌘ ,','Paramètres'],['P','Pomodoro'],['L','Verrouiller LifeOS']].map(([keys,label])=><div key={label}><span>{label}</span><kbd>{keys}</kbd></div>)}</div></SettingsBlock>
}

function DashboardSettings(){const visible=useDashboardStore((s)=>s.visible),toggle=useDashboardStore((s)=>s.toggleWidget),edit=useDashboardStore((s)=>s.editMode),setEdit=useDashboardStore((s)=>s.setEditMode),reset=useDashboardStore((s)=>s.resetLayout);return <SettingsBlock title="Organisation du dashboard" description="Activez, masquez et réorganisez chaque module."><ToggleRow label="Mode personnalisation" text="Autoriser le glisser-déposer et le redimensionnement" value={edit} onChange={setEdit}/><div className="settings-modules">{modules.map((item)=><div key={item.id}><span><item.icon size={17}/>{item.label}<small>{item.category}</small></span><Toggle checked={visible[item.id]!==false} onChange={()=>toggle(item.id)} label={`Afficher ${item.label}`}/></div>)}</div><Button variant="secondary" onClick={()=>confirm('Réinitialiser tous les modules ?')&&reset()}><LayoutGrid size={16}/>Réinitialiser la disposition</Button></SettingsBlock>}

function DataSettings(){
  const inputRef=useRef<HTMLInputElement>(null),showToast=useUIStore((s)=>s.showToast),setView=useUIStore((s)=>s.setView)
  const backup=()=>{
    const data={exportedAt:new Date().toISOString(),version:2,settings:useSettingsStore.getState(),finance:useFinanceStore.getState(),personal:usePersonalStore.getState(),dashboard:useDashboardStore.getState()}
    downloadFile('lifeos-donnees.json',JSON.stringify(data,null,2),'application/json')
    localStorage.setItem('lifeos:last-backup',new Date().toISOString());showToast('Sauvegarde téléchargée')
  }
  const restore=(file?:File)=>{
    if(!file)return
    file.text().then((text)=>{
      try{
        const d=JSON.parse(text)
        if(d.settings)localStorage.setItem('lifeos:v2:settings',JSON.stringify({state:d.settings,version:0}))
        if(d.finance)localStorage.setItem('lifeos:v2:finance',JSON.stringify({state:d.finance,version:0}))
        if(d.personal)localStorage.setItem('lifeos:v2:personal',JSON.stringify({state:d.personal,version:0}))
        if(d.dashboard)localStorage.setItem('lifeos:v2:dashboard',JSON.stringify({state:d.dashboard,version:0}))
        showToast('Données restaurées');setTimeout(()=>location.reload(),700)
      }catch{showToast('Fichier invalide')}
    })
  }
  return <SettingsBlock title="Vos données" description="Importez, exportez ou réinitialisez vos données en toute autonomie."><div className="data-actions"><button onClick={()=>{sessionStorage.setItem('lifeos:open-tool','bank');setView('tools')}}><FileSpreadsheet/><span><b>Personnaliser avec Excel</b><small>Analyse intelligente XLSX ou CSV</small></span></button><button onClick={backup}><Download/><span><b>Exporter toutes les données</b><small>Fichier JSON portable</small></span></button><button onClick={()=>inputRef.current?.click()}><Upload/><span><b>Restaurer une sauvegarde</b><small>Depuis un fichier JSON</small></span></button><input ref={inputRef} hidden type="file" accept=".json,application/json" onChange={(e)=>restore(e.target.files?.[0])}/><button onClick={()=>{localStorage.setItem('lifeos:manual-backup',JSON.stringify(Object.fromEntries(Object.entries(localStorage).filter(([k])=>k.startsWith('lifeos:')))));localStorage.setItem('lifeos:last-backup',new Date().toISOString());showToast('Instantané local créé')}}><Save/><span><b>Instantané local</b><small>Dans ce navigateur</small></span></button></div><div className="danger-zone"><span><b>Zone de réinitialisation</b><small>Cette action supprime toutes les données LifeOS locales.</small></span><Button variant="danger" onClick={()=>{if(prompt('Tapez SUPPRIMER pour confirmer')==='SUPPRIMER'){Object.keys(localStorage).filter(k=>k.startsWith('lifeos')).forEach(k=>localStorage.removeItem(k));location.reload()}}}><Trash2 size={16}/>Réinitialiser</Button></div></SettingsBlock>
}

function SettingsBlock({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="settings-block"><header><h2>{title}</h2><p>{description}</p></header><div>{children}</div></section>}
function SettingGroup({title,children}:{title:string;children:React.ReactNode}){return <div className="setting-group"><h3>{title}</h3>{children}</div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
function ToggleRow({label,text,value,onChange,icon}:{label:string;text:string;value:boolean;onChange:(v:boolean)=>void;icon?:React.ReactNode}){return <div className="toggle-row"><span>{icon}{<span><b>{label}</b><small>{text}</small></span>}</span><Toggle checked={value} onChange={onChange} label={label}/></div>}
function ChoiceCards({options,value,onChange}:{options:{id:string;label:string;hint:string}[];value:string;onChange:(id:string)=>void}){return <div className="choice-cards">{options.map((item)=><button key={item.id} className={value===item.id?'active':''} onClick={()=>onChange(item.id)}><span className="choice-preview"/><b>{item.label}</b><small>{item.hint}</small>{value===item.id&&<Check size={15}/>}</button>)}</div>}
