import { useMemo, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { AlertTriangle, Bot, CalendarSync, Check, Cloud, Code2, Download, FileBarChart, FileCheck2, FileSpreadsheet, Gift, Mail, Palette, RefreshCw, ShieldCheck, Smartphone, Sparkles, TableProperties, Upload, Users } from 'lucide-react'
import { defaultLayout, useDashboardStore, useFinanceStore, usePersonalStore, useSettingsStore, useUIStore } from '../../store'
import { modules, type ModuleId } from '../../data/modules'
import type { ExcelImportPlan, ExcelSheet } from '../../utils/excel'
import { downloadFile, formatCurrency, transactionsToCSV } from '../../utils/helpers'
import { Badge, Button, Input, Modal, Progress } from '../ui'

type ToolId = 'ai' | 'reports' | 'bank' | 'cloud' | 'family' | 'integrations' | 'offline' | 'themes' | 'api' | 'automation' | 'vault' | 'support'
const tools: { id: ToolId; title: string; description: string; icon: typeof Bot; tag: string }[] = [
  { id: 'ai', title: 'Prévisions intelligentes', description: 'Projection locale de votre solde et détection des tendances.', icon: Bot, tag: 'IA locale' },
  { id: 'reports', title: 'Rapports PDF & CSV', description: 'Bilans complets prêts à imprimer ou exporter.', icon: FileBarChart, tag: 'Exports' },
  { id: 'bank', title: 'Import Excel intelligent', description: 'Analyse vos feuilles et adapte automatiquement les modules LifeOS.', icon: FileSpreadsheet, tag: 'XLSX + CSV' },
  { id: 'cloud', title: 'Sauvegarde portable', description: 'Téléchargez et restaurez toutes vos données LifeOS.', icon: Cloud, tag: 'Sans serveur' },
  { id: 'family', title: 'Espace famille', description: 'Créez des profils et répartissez les objectifs communs.', icon: Users, tag: 'Multi-profils' },
  { id: 'integrations', title: 'Calendriers externes', description: 'Exportez vos événements vers Google, Outlook ou Apple.', icon: CalendarSync, tag: 'Format ICS' },
  { id: 'offline', title: 'Mode hors connexion', description: 'Continuez à consulter vos données sans réseau.', icon: Smartphone, tag: 'PWA' },
  { id: 'themes', title: 'Thèmes personnalisés', description: 'Smoke, sauge, ardoise ou terre cuite.', icon: Palette, tag: '4 palettes' },
  { id: 'api', title: 'API développeur locale', description: 'Accédez aux données depuis la console et vos scripts.', icon: Code2, tag: 'JavaScript' },
  { id: 'automation', title: 'Automatisations', description: 'Rappels de revue, budget et habitudes programmés.', icon: RefreshCw, tag: 'Routines' },
  { id: 'vault', title: 'Coffre de données', description: 'Contrôle local, export et effacement transparent.', icon: ShieldCheck, tag: 'Vie privée' },
  { id: 'support', title: 'Centre d’aide', description: 'Guide intégré et diagnostic de votre installation.', icon: Mail, tag: 'Disponible' },
]

function exportAll() {
  const payload = { exportedAt: new Date().toISOString(), version: 2, settings: useSettingsStore.getState(), finance: useFinanceStore.getState(), personal: usePersonalStore.getState() }
  downloadFile(`lifeos-backup-${new Date().toISOString().slice(0,10)}.json`, JSON.stringify(payload, null, 2), 'application/json')
}

export function ToolsPage() {
  const [selected, setSelected] = useState<ToolId | null>(() => { const requested=sessionStorage.getItem('lifeos:open-tool') as ToolId|null;sessionStorage.removeItem('lifeos:open-tool');return tools.some((tool)=>tool.id===requested)?requested:null })
  return <motion.div className="page tools-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
    <section className="tools-hero"><div className="tools-hero-copy"><Badge tone="free"><Gift size={12}/> 100 % INCLUS</Badge><h1>Tous les outils.<br/><span>Aucune barrière.</span></h1><p>LifeOS vous appartient. Toutes les fonctionnalités sont disponibles pour vous et tous les utilisateurs, librement et sans aucune barrière.</p><div className="hero-checks"><span><Check/>Accès illimité</span><span><Check/>Données locales</span><span><Check/>Tout est inclus</span></div></div><div className="free-seal"><span><Sparkles size={28}/></span><strong>GRATUIT</strong><small>POUR TOUJOURS</small></div></section>
    <div className="tools-heading"><div><span className="eyebrow">BOÎTE À OUTILS</span><h2>Choisissez un outil pour l’ouvrir</h2><p>Chaque carte mène directement à un espace pleinement fonctionnel.</p></div><Badge tone="free">12 OUTILS ACTIFS</Badge></div>
    <div className="tools-grid">{tools.map((tool, index) => <motion.button key={tool.id} className="tool-card" onClick={() => setSelected(tool.id)} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} whileHover={{ y: -5 }}><span className="tool-icon"><tool.icon size={22}/></span><span className="free-corner"><Check size={11}/> GRATUIT</span><div><Badge>{tool.tag}</Badge><h3>{tool.title}</h3><p>{tool.description}</p></div><footer><span>Ouvrir l’outil</span><i>→</i></footer></motion.button>)}</div>
    <section className="ownership"><ShieldCheck size={28}/><div><h3>Vos données restent les vôtres.</h3><p>Aucune donnée financière ou personnelle n’est envoyée à un serveur LifeOS. La persistance s’effectue dans votre navigateur et les exports sont déclenchés par vous.</p></div><Button variant="secondary" onClick={exportAll}><Download size={16}/>Sauvegarder maintenant</Button></section>
    <ToolModal selected={selected} onClose={() => setSelected(null)}/>
  </motion.div>
}

function ToolModal({ selected, onClose }: { selected: ToolId | null; onClose: () => void }) {
  const tool = tools.find((item) => item.id === selected)
  return <Modal open={!!tool} onClose={onClose} title={tool?.title ?? ''} width="760px">{selected && <ToolWorkspace id={selected}/>}</Modal>
}

function ToolWorkspace({ id }: { id: ToolId }) {
  const transactions = useFinanceStore((s) => s.transactions), currency = useSettingsStore((s) => s.currency), settings = useSettingsStore(), update = useSettingsStore((s) => s.update), events = usePersonalStore((s) => s.events), showToast = useUIStore((s) => s.showToast)
  const fileRef = useRef<HTMLInputElement>(null); const [family, setFamily] = useState(() => JSON.parse(localStorage.getItem('lifeos:family') ?? '["Mourad"]') as string[]); const [name, setName] = useState('')
  const prediction = useMemo(() => { const expense = transactions.filter((t) => t.type === 'expense').reduce((s,t)=>s+t.amount,0) / 6; const income = transactions.filter((t) => t.type === 'income').reduce((s,t)=>s+t.amount,0) / 6; return Array.from({length:6},(_,i)=>({ month:`M+${i+1}`, balance:Math.round((income-expense)*(i+1)*Math.pow(1.01,i)) })) }, [transactions])
  const restore = (file?: File) => { if (!file) return; file.text().then((text) => { try { const data=JSON.parse(text); if(data.finance?.transactions) localStorage.setItem('lifeos:v2:finance', JSON.stringify({ state: data.finance, version: 0 })); if(data.personal) localStorage.setItem('lifeos:v2:personal', JSON.stringify({ state:data.personal, version:0 })); showToast('Sauvegarde restaurée — rechargement…'); setTimeout(()=>location.reload(),700) } catch { showToast('Fichier de sauvegarde invalide') } }) }
  const exportICS = () => { const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LifeOS//FR',...events.flatMap((e)=>['BEGIN:VEVENT',`UID:${e.id}@lifeos`,`DTSTART:${e.date.replaceAll('-','')}T${e.time.replace(':','')}00`,`SUMMARY:${e.title}`,'END:VEVENT']),'END:VCALENDAR'].join('\r\n'); downloadFile('lifeos-calendrier.ics',body,'text/calendar') }
  if (id === 'ai') return <div className="tool-workspace"><p className="workspace-intro">Prévision calculée localement à partir de votre historique. Le modèle extrapole votre épargne moyenne avec une amélioration prudente de 1 % par mois.</p><div className="prediction-summary"><span><small>Solde projeté à 6 mois</small><strong>{formatCurrency(prediction[5].balance,currency,settings.hideAmounts)}</strong></span><Badge tone="success">Tendance positive</Badge></div><div className="workspace-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={prediction}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="month"/><YAxis hide/><Area type="monotone" dataKey="balance" stroke="var(--accent)" fill="var(--accent-soft)"/><Tooltip formatter={(v:number)=>formatCurrency(v,currency,settings.hideAmounts)}/></AreaChart></ResponsiveContainer></div><div className="insight"><Sparkles/><span><b>Conseil personnalisé</b>Automatisez 15 % du prochain revenu freelance pour atteindre votre fonds d’urgence environ un mois plus tôt.</span></div></div>
  if (id === 'reports') return <div className="tool-workspace"><p className="workspace-intro">Générez un rapport financier imprimable ou exportez toutes les lignes dans un format compatible Excel.</p><div className="report-preview"><span><FileBarChart size={32}/></span><div><b>Rapport LifeOS — {new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date())}</b><small>{transactions.length} transactions · {usePersonalStore.getState().tasks.length} tâches · {usePersonalStore.getState().goals.length} objectifs</small></div></div><div className="workspace-actions"><Button onClick={()=>window.print()}><FileBarChart size={16}/>Imprimer / Enregistrer en PDF</Button><Button variant="secondary" onClick={()=>downloadFile('rapport-lifeos.csv',transactionsToCSV(transactions),'text/csv;charset=utf-8')}><Download size={16}/>Exporter pour Excel</Button></div></div>
  if (id === 'bank') return <ExcelImportWorkspace/>
  if (id === 'cloud') return <div className="tool-workspace"><p className="workspace-intro">Une sauvegarde portable contient vos paramètres, finances et données personnelles. Stockez-la où vous voulez.</p><div className="backup-status"><Cloud size={30}/><span><b>Prêt à sauvegarder</b><small>{new Blob([JSON.stringify({transactions})]).size.toLocaleString('fr-FR')} octets estimés</small></span><Badge tone="success">Local</Badge></div><div className="workspace-actions"><Button onClick={exportAll}><Download size={16}/>Télécharger la sauvegarde</Button><Button variant="secondary" onClick={()=>fileRef.current?.click()}><Upload size={16}/>Restaurer un fichier</Button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={(e)=>restore(e.target.files?.[0])}/></div></div>
  if (id === 'family') return <div className="tool-workspace"><p className="workspace-intro">Créez des profils locaux pour organiser les responsabilités et objectifs communs.</p><div className="family-list">{family.map((member,i)=><div key={`${member}-${i}`}><span>{member.slice(0,1).toUpperCase()}</span><b>{member}</b><small>{i===0?'Administrateur':'Membre'}</small>{i>0&&<button onClick={()=>{const next=family.filter((_,x)=>x!==i);setFamily(next);localStorage.setItem('lifeos:family',JSON.stringify(next))}}>Retirer</button>}</div>)}</div><div className="inline-form"><Input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Nom du membre"/><Button disabled={!name.trim()} onClick={()=>{const next=[...family,name.trim()];setFamily(next);localStorage.setItem('lifeos:family',JSON.stringify(next));setName('')}}><Users size={16}/>Ajouter</Button></div></div>
  if (id === 'integrations') return <div className="tool-workspace"><p className="workspace-intro">Le format universel ICS s’importe dans Google Calendar, Outlook et Apple Calendar.</p><div className="integration-list">{['Google Calendar','Microsoft Outlook','Apple Calendar'].map((item)=><div key={item}><CalendarSync/><span><b>{item}</b><small>{events.length} événements prêts</small></span><Badge tone="success">Compatible</Badge></div>)}</div><Button onClick={exportICS}><Download size={16}/>Exporter mon calendrier .ics</Button></div>
  if (id === 'offline') return <div className="tool-workspace"><p className="workspace-intro">LifeOS mémorise déjà toutes vos données localement. Une fois l’application chargée, vos données restent consultables sans compte.</p><div className="capability-grid"><div><Check/><b>Stockage local</b><span>Actif</span></div><div><Check/><b>Responsive mobile</b><span>Actif</span></div><div><Check/><b>Export portable</b><span>Actif</span></div><div><Check/><b>Installation</b><span>Menu du navigateur</span></div></div><Button onClick={()=>showToast('Dans Chrome : menu ⋮ → Installer LifeOS / Ajouter à l’écran d’accueil')}>Afficher les instructions d’installation</Button></div>
  if (id === 'themes') return <div className="tool-workspace"><p className="workspace-intro">Sélectionnez une ambiance. Le choix est appliqué immédiatement et conservé.</p><div className="theme-picker">{(['smoke','sage','slate','terracotta'] as const).map((accent)=><button key={accent} className={`${accent} ${settings.accent===accent?'active':''}`} onClick={()=>update({accent})}><i/><span><b>{accent==='smoke'?'Fumée':accent==='sage'?'Sauge':accent==='slate'?'Ardoise':'Terre cuite'}</b><small>{settings.accent===accent?'Thème actif':'Appliquer'}</small></span>{settings.accent===accent&&<Check/>}</button>)}</div></div>
  if (id === 'api') return <div className="tool-workspace"><p className="workspace-intro">LifeOS expose ses stores côté navigateur. Utilisez l’export JSON comme API portable ou interrogez localStorage.</p><pre className="code-block"><code>{`// Lire les données financières LifeOS\nconst raw = localStorage.getItem('lifeos:v2:finance')\nconst { state } = JSON.parse(raw)\nconsole.log(state.transactions)\n\n// Écouter les changements\nwindow.addEventListener('storage', (event) => {\n  if (event.key?.startsWith('lifeos:')) sync(event)\n})`}</code></pre><Button onClick={()=>{navigator.clipboard.writeText("localStorage.getItem('lifeos:v2:finance')");showToast('Exemple copié')}}><Code2 size={16}/>Copier l’exemple</Button></div>
  if (id === 'automation') return <div className="tool-workspace"><p className="workspace-intro">Activez vos routines. Les paramètres sont appliqués par le coach LifeOS lors de vos visites.</p><div className="automation-list">{[['Revue du budget','Chaque vendredi à 18:00'],['Bilan des habitudes','Chaque dimanche à 20:00'],['Plan du jour','Tous les jours à 09:00']].map(([title,time])=><label key={title}><span><RefreshCw/><span><b>{title}</b><small>{time}</small></span></span><input type="checkbox" defaultChecked/></label>)}</div><Button onClick={()=>showToast('Automatisations enregistrées')}><Check size={16}/>Enregistrer les routines</Button></div>
  if (id === 'vault') return <div className="tool-workspace"><p className="workspace-intro">Transparence complète : vos données vivent dans ce navigateur. Vous pouvez les exporter ou les effacer à tout moment.</p><div className="vault-stats"><div><b>{Object.keys(localStorage).filter((k)=>k.startsWith('lifeos')).length}</b><span>espaces de stockage</span></div><div><b>{transactions.length}</b><span>transactions locales</span></div><div><b>0</b><span>transfert serveur</span></div></div><div className="workspace-actions"><Button onClick={exportAll}><Download size={16}/>Exporter tout</Button><Button variant="danger" onClick={()=>{if(confirm('Effacer toutes les données LifeOS de ce navigateur ?')){Object.keys(localStorage).filter(k=>k.startsWith('lifeos')).forEach(k=>localStorage.removeItem(k));location.reload()}}}>Effacer mes données</Button></div></div>
  return <div className="tool-workspace"><p className="workspace-intro">LifeOS inclut un diagnostic rapide et une aide intégrée, disponibles pour tous.</p><div className="diagnostic"><div><Check/><span><b>Navigateur compatible</b><small>{navigator.userAgent.split(' ').slice(-2).join(' ')}</small></span></div><div><Check/><span><b>Stockage disponible</b><small>localStorage opérationnel</small></span></div><div><Check/><span><b>Application à jour</b><small>LifeOS v2.1</small></span></div></div><a className="button button-primary button-md" href="mailto:mouradghazi002@gmail.com?subject=Aide%20LifeOS"><Mail size={16}/>Contacter le support</a></div>
}

type ImportMode = 'replace' | 'merge'

function mergeRecords<T>(current: T[], incoming: T[], key: (item: T) => string, mode: ImportMode) {
  if (mode === 'replace') return incoming
  const seen = new Set<string>()
  return [...incoming, ...current].filter((item) => { const value=key(item).toLowerCase(); if(seen.has(value))return false;seen.add(value);return true })
}

function personalizedLayout(priority: ModuleId[]) {
  const order=[...new Set<ModuleId>(['clock','weather','pomodoro',...priority,...modules.map((module)=>module.id)])]
  let x=0,y=0,rowHeight=0
  return order.map((id)=>defaultLayout.find((item)=>item.i===id)).filter((item):item is NonNullable<typeof item>=>!!item).map((item)=>{if(x+item.w>12){x=0;y+=rowHeight;rowHeight=0}const next={...item,x,y};x+=item.w;rowHeight=Math.max(rowHeight,item.h);return next})
}

function applyExcelPlan(plan: ExcelImportPlan, mode: ImportMode, adaptDashboard: boolean) {
  const personal=usePersonalStore.getState(),finance=useFinanceStore.getState()
  const personalPatch: Partial<typeof personal>={},financePatch:Partial<typeof finance>={}
  if(plan.tasks.length)personalPatch.tasks=mergeRecords(personal.tasks,plan.tasks,(item)=>`${item.title}|${item.dueDate}`,mode)
  if(plan.events.length)personalPatch.events=mergeRecords(personal.events,plan.events,(item)=>`${item.title}|${item.date}|${item.time}`,mode)
  if(plan.goals.length)personalPatch.goals=mergeRecords(personal.goals,plan.goals,(item)=>`${item.title}|${item.deadline}`,mode)
  if(plan.habits.length)personalPatch.habits=mergeRecords(personal.habits,plan.habits,(item)=>item.name,mode)
  if(plan.notes.length)personalPatch.notes=mergeRecords(personal.notes,plan.notes,(item)=>`${item.title}|${item.content}`,mode)
  if(plan.journal.length)personalPatch.journal=mergeRecords(personal.journal,plan.journal,(item)=>`${item.date}|${item.content}`,mode)
  if(plan.transactions.length)financePatch.transactions=mergeRecords(finance.transactions,plan.transactions,(item)=>`${item.date}|${item.title}|${item.amount}|${item.type}`,mode)
  if(plan.budgets.length)financePatch.budgets=mergeRecords(finance.budgets,plan.budgets,(item)=>item.category,mode)
  if(plan.savingsGoals.length)financePatch.savingsGoals=mergeRecords(finance.savingsGoals,plan.savingsGoals,(item)=>item.name,mode)
  if(plan.investments.length)financePatch.investments=mergeRecords(finance.investments,plan.investments,(item)=>`${item.name}|${item.symbol}`,mode)
  usePersonalStore.setState(personalPatch);useFinanceStore.setState(financePatch)
  if(Object.keys(plan.profile).length)useSettingsStore.getState().updateProfile(plan.profile)
  if(Object.keys(plan.settings).length)useSettingsStore.getState().update(plan.settings)
  if(adaptDashboard){const core=new Set<ModuleId>(['clock','weather','pomodoro']),active=new Set<ModuleId>([...core,...plan.widgets]);const visible=Object.fromEntries(modules.map((module)=>[module.id,active.has(module.id)]));useDashboardStore.setState({visible,layout:personalizedLayout(plan.widgets)})}
}

function downloadExcelTemplate() {
  import('../../utils/excel').then(({createLifeOSExcelTemplate})=>{const url=URL.createObjectURL(new Blob([createLifeOSExcelTemplate()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),anchor=document.createElement('a');anchor.href=url;anchor.download='modele-personnalisation-lifeos.xlsx';anchor.click();URL.revokeObjectURL(url)})
}

function SheetPreview({ sheet }: { sheet: ExcelSheet }) {
  const rows=sheet.rows.slice(0,7),columnCount=Math.min(10,Math.max(1,...rows.map((row)=>row.length)))
  return <div className="excel-preview-table" role="region" aria-label={`Aperçu de ${sheet.name}`}><table><tbody>{rows.map((row,rowIndex)=><tr key={rowIndex}>{Array.from({length:columnCount},(_,column)=><td key={column} className={rowIndex===0?'header-cell':''}>{String(row[column]??'')}</td>)}</tr>)}</tbody></table></div>
}

function ExcelImportWorkspace() {
  const inputRef=useRef<HTMLInputElement>(null),showToast=useUIStore((s)=>s.showToast),setView=useUIStore((s)=>s.setView)
  const [plan,setPlan]=useState<ExcelImportPlan|null>(null),[fileName,setFileName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState<ImportMode>('replace'),[adapt,setAdapt]=useState(true),[sheetIndex,setSheetIndex]=useState(0),[applied,setApplied]=useState(false)
  const analyze=async(file?:File)=>{if(!file)return;setBusy(true);setError('');setPlan(null);setApplied(false);setFileName(file.name);try{const {parseExcelFile,buildExcelImportPlan}=await import('../../utils/excel');const workbook=await parseExcelFile(file),next=buildExcelImportPlan(workbook);setPlan(next);setSheetIndex(0);if(!next.detected.length)setError('Le classeur est lisible, mais aucune structure LifeOS n’a été reconnue. Consultez le modèle pour les noms de colonnes recommandés.')}catch(reason){setError(reason instanceof Error?reason.message:'Impossible de lire ce fichier Excel.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
  const apply=()=>{if(!plan||!plan.totalRecords)return;applyExcelPlan(plan,mode,adapt);localStorage.setItem('lifeos:last-excel-import',JSON.stringify({file:fileName,at:new Date().toISOString(),records:plan.totalRecords,sheets:plan.workbook.sheets.length,formulas:plan.workbook.formulaCount,detected:plan.detected}));setApplied(true);showToast(`${plan.totalRecords} donnée(s) importée(s) — dashboard personnalisé`)}
  const selectedSheet=plan?.workbook.sheets[Math.min(sheetIndex,(plan?.workbook.sheets.length??1)-1)]
  return <div className="tool-workspace excel-importer">
    <div className="excel-intro"><span><FileSpreadsheet size={26}/></span><div><b>Votre classeur devient votre LifeOS</b><p>LifeOS lit localement les feuilles, les valeurs et les résultats enregistrés des formules, puis reconnaît automatiquement transactions, tâches, événements, budgets, épargne, objectifs, habitudes, notes et profil.</p></div><Badge tone="success"><ShieldCheck size={12}/>100 % local</Badge></div>
    {!plan&&!busy&&<><div className="drop-zone excel-drop" role="button" tabIndex={0} onClick={()=>inputRef.current?.click()} onKeyDown={(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();inputRef.current?.click()}}} onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();analyze(event.dataTransfer.files[0])}}><Upload size={32}/><b>Déposez votre fichier Excel ici</b><span>.xlsx, .xlsm ou .csv · 25 Mo maximum</span><Button type="button" size="sm">Choisir un fichier</Button></div><input ref={inputRef} type="file" accept=".xlsx,.xlsm,.xltx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" hidden onChange={(event)=>analyze(event.target.files?.[0])}/><div className="excel-template"><TableProperties size={20}/><span><b>Vous partez de zéro ?</b><small>Le modèle contient 11 feuilles déjà structurées pour LifeOS.</small></span><Button variant="secondary" size="sm" onClick={downloadExcelTemplate}><Download size={15}/>Télécharger le modèle Excel</Button></div></>}
    {busy&&<div className="excel-loading"><RefreshCw className="spin" size={30}/><b>Analyse de « {fileName} »…</b><span>Lecture des feuilles, cellules, dates et formules sans envoi réseau.</span><Progress value={70}/></div>}
    {error&&<div className="excel-warning"><AlertTriangle size={18}/><span><b>Analyse incomplète</b>{error}</span>{plan&&<Button size="sm" variant="secondary" onClick={()=>{setPlan(null);setError('')}}>Choisir un autre fichier</Button>}</div>}
    {plan&&<>
      <div className="excel-file-summary"><span className="excel-file-icon"><FileCheck2 size={25}/></span><span><b>{fileName}</b><small>Classeur analysé avec succès dans votre navigateur</small></span><div><b>{plan.workbook.sheets.length}</b><small>feuilles</small></div><div><b>{plan.totalRecords}</b><small>données</small></div><div><b>{plan.workbook.formulaCount}</b><small>formules</small></div><Button size="sm" variant="ghost" onClick={()=>{setPlan(null);setError('');setApplied(false)}}>Changer</Button></div>
      <section className="excel-section"><header><span><Sparkles size={17}/><b>Modules détectés</b></span><small>{plan.detected.length} structure(s) reconnue(s)</small></header><div className="detected-grid">{plan.detected.map((item,index)=><div key={`${item.sheet}-${item.kind}-${index}`}><Check size={15}/><span><b>{item.label}</b><small>Feuille « {item.sheet} » · en-têtes ligne {item.headerRow}</small></span><Badge tone={item.count?'success':'neutral'}>{item.count}</Badge></div>)}</div></section>
      <section className="excel-section"><header><span><TableProperties size={17}/><b>Aperçu du classeur</b></span><select className="tiny-select" value={sheetIndex} onChange={(event)=>setSheetIndex(Number(event.target.value))}>{plan.workbook.sheets.map((sheet,index)=><option key={`${sheet.name}-${index}`} value={index}>{sheet.name}</option>)}</select></header>{selectedSheet&&<SheetPreview sheet={selectedSheet}/>} {selectedSheet?.formulas.length?<details className="formula-details"><summary>{selectedSheet.formulas.length} formule(s) dans cette feuille</summary>{selectedSheet.formulas.slice(0,8).map((formula)=><code key={formula.cell}>{formula.cell} = {formula.formula} → {String(formula.cachedValue??'sans résultat enregistré')}</code>)}</details>:null}</section>
      {plan.warnings.length>0&&<div className="excel-notes">{plan.warnings.map((warning,index)=><p key={index}><AlertTriangle size={14}/>{warning}</p>)}</div>}
      <section className="excel-import-options"><div><b>Comment intégrer les données ?</b><label><input type="radio" name="excel-mode" checked={mode==='replace'} onChange={()=>setMode('replace')}/><span><strong>Remplacer les données de démonstration</strong><small>Uniquement pour les modules détectés dans le classeur</small></span></label><label><input type="radio" name="excel-mode" checked={mode==='merge'} onChange={()=>setMode('merge')}/><span><strong>Fusionner avec mes données</strong><small>Les doublons identiques sont automatiquement ignorés</small></span></label></div><label className="adapt-dashboard"><input type="checkbox" checked={adapt} onChange={(event)=>setAdapt(event.target.checked)}/><span><strong>Adapter mon dashboard</strong><small>Affiche et remonte en priorité les widgets correspondant au fichier</small></span></label></section>
      <div className="excel-actions">{applied?<><div className="excel-success"><Check size={18}/><span><b>Personnalisation terminée</b><small>Les données sont enregistrées localement.</small></span></div><Button onClick={()=>setView('dashboard')}>Voir mon dashboard →</Button></>:<><Button variant="secondary" onClick={downloadExcelTemplate}><Download size={15}/>Modèle Excel</Button><Button disabled={!plan.totalRecords} onClick={apply}><Sparkles size={16}/>Personnaliser LifeOS avec {plan.totalRecords} donnée(s)</Button></>}</div>
    </>}
  </div>
}
