import { useEffect, useState } from 'react'
import { CalendarDays, CheckSquare2, CircleDollarSign, Command, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { useChatbotStore, useFinanceStore, usePersonalStore, useSettingsStore, useUIStore } from '../../store'
import type { Priority, TransactionType, View } from '../../types'
import { Button, Input, Modal, Select } from '../ui'

export function GlobalActions(){
  const modal=useUIStore(s=>s.modal),setModal=useUIStore(s=>s.setModal),showToast=useUIStore(s=>s.showToast),setView=useUIStore(s=>s.setView),theme=useSettingsStore(s=>s.theme),update=useSettingsStore(s=>s.update)
  const [palette,setPalette]=useState(false)
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('.global-search input')?.focus()}if(mod&&e.key.toLowerCase()==='t'){e.preventDefault();setModal('task')}if(mod&&e.key.toLowerCase()==='m'){e.preventDefault();setModal('transaction')}if(mod&&e.key.toLowerCase()==='n'){e.preventDefault();usePersonalStore.getState().addNote();setView('personal');showToast('Note créée')}if(mod&&e.key==='/'){e.preventDefault();useChatbotStore.getState().setOpen(true)}if(mod&&e.shiftKey&&e.key.toLowerCase()==='l'){e.preventDefault();update({theme:theme==='light'?'dark':theme==='dark'?'auto':'light'})}if(mod&&e.key===','){e.preventDefault();setView('settings')}if(mod&&e.key.toLowerCase()==='p'){e.preventDefault();setPalette(true)}const target=e.target as HTMLElement;const isTyping=['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable;if(!mod&&!isTyping&&e.key.toLowerCase()==='l'){e.preventDefault();useUIStore.getState().setLocked(true)}if(!mod&&!isTyping&&e.key.toLowerCase()==='p'){e.preventDefault();setView('dashboard');setTimeout(()=>document.getElementById('module-pomodoro')?.scrollIntoView({behavior:'smooth',block:'center'}),100)}};addEventListener('keydown',handler);return()=>removeEventListener('keydown',handler)},[setModal,setView,showToast,theme,update])
  return <><AnimatePresence mode="wait">{modal==='task'&&<TaskModal close={()=>setModal(null)}/>} {modal==='transaction'&&<TransactionModal close={()=>setModal(null)}/>} {modal==='event'&&<EventModal close={()=>setModal(null)}/>}</AnimatePresence>{palette&&<CommandPalette close={()=>setPalette(false)} go={(v)=>{setView(v);setPalette(false)}}/>}</>
}
function TaskModal({close}:{close:()=>void}){const add=usePersonalStore(s=>s.addTask),toast=useUIStore(s=>s.showToast);return <Modal open title="Nouvelle tâche" onClose={close}><form className="modal-form" onSubmit={(e)=>{e.preventDefault();const d=new FormData(e.currentTarget);add(String(d.get('title')),{category:String(d.get('category')),priority:String(d.get('priority')) as Priority,dueDate:String(d.get('date'))});toast('Tâche ajoutée');close()}}><div className="modal-icon task"><CheckSquare2/></div><Field label="Titre"><Input name="title" required autoFocus placeholder="Que souhaitez-vous accomplir ?"/></Field><div className="form-grid"><Field label="Catégorie"><Select name="category" defaultValue="Travail"><option>Travail</option><option>Personnel</option><option>Santé</option><option>Finance</option><option>Apprentissage</option><option>Maison</option></Select></Field><Field label="Priorité"><Select name="priority" defaultValue="medium"><option value="low">Basse</option><option value="medium">Moyenne</option><option value="high">Haute</option><option value="urgent">Urgente</option></Select></Field><Field label="Échéance" wide><Input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field></div><Actions close={close} label="Créer la tâche"/></form></Modal>}
function TransactionModal({close}:{close:()=>void}){const add=useFinanceStore(s=>s.addTransaction),toast=useUIStore(s=>s.showToast);return <Modal open title="Nouvelle transaction" onClose={close}><form className="modal-form" onSubmit={(e)=>{e.preventDefault();const d=new FormData(e.currentTarget);add({title:String(d.get('title')),amount:Number(d.get('amount')),type:String(d.get('type')) as TransactionType,category:String(d.get('category')),date:String(d.get('date')),note:String(d.get('note'))});toast('Transaction enregistrée');close()}}><div className="modal-icon money"><CircleDollarSign/></div><Field label="Libellé"><Input name="title" required autoFocus placeholder="Ex. Courses, salaire…"/></Field><div className="form-grid"><Field label="Montant"><Input name="amount" type="number" min="0" step="0.01" required placeholder="0"/></Field><Field label="Type"><Select name="type" defaultValue="expense"><option value="expense">Dépense</option><option value="income">Revenu</option></Select></Field><Field label="Catégorie"><Select name="category" defaultValue="Alimentation"><option>Salaire</option><option>Freelance</option><option>Logement</option><option>Alimentation</option><option>Transport</option><option>Loisirs</option><option>Santé</option><option>Abonnements</option><option>Formation</option><option>Autres</option></Select></Field><Field label="Date"><Input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></Field><Field label="Note" wide><Input name="note" placeholder="Optionnel"/></Field></div><Actions close={close} label="Ajouter la transaction"/></form></Modal>}
function EventModal({close}:{close:()=>void}){const add=usePersonalStore(s=>s.addEvent),toast=useUIStore(s=>s.showToast);return <Modal open title="Nouvel événement" onClose={close}><form className="modal-form" onSubmit={(e)=>{e.preventDefault();const d=new FormData(e.currentTarget);add({title:String(d.get('title')),date:String(d.get('date')),time:String(d.get('time')),color:String(d.get('color'))});toast('Événement ajouté');close()}}><div className="modal-icon event"><CalendarDays/></div><Field label="Titre"><Input name="title" required autoFocus placeholder="Nom de l’événement"/></Field><div className="form-grid"><Field label="Date"><Input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></Field><Field label="Heure"><Input name="time" type="time" required defaultValue="09:00"/></Field><Field label="Couleur" wide><Select name="color"><option value="#343a40">Fumée</option><option value="#5f6b62">Sauge</option><option value="#8a7563">Terre</option><option value="#64748b">Ardoise</option></Select></Field></div><Actions close={close} label="Ajouter au calendrier"/></form></Modal>}
function Actions({close,label}:{close:()=>void;label:string}){return <div className="modal-actions"><Button variant="ghost" type="button" onClick={close}>Annuler</Button><Button type="submit">{label}</Button></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
function CommandPalette({close,go}:{close:()=>void;go:(v:View)=>void}){const [query,setQuery]=useState(''),actions:[View,string,string][]=[['dashboard','Vue d’ensemble','D'],['finances','Finances','F'],['personal','Vie personnelle','V'],['tools','Outils gratuits','O'],['settings','Paramètres','S']],filtered=actions.filter(([,label,key])=>`${label} ${key}`.toLowerCase().includes(query.toLowerCase()));return <motion.div className="command-backdrop" role="dialog" aria-label="Navigation rapide" initial={{opacity:0}} animate={{opacity:1}} onMouseDown={close}><motion.div className="command-palette" initial={{scale:.96,y:-15}} animate={{scale:1,y:0}} onMouseDown={e=>e.stopPropagation()}><header><Command size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Enter'&&filtered[0])go(filtered[0][0])}} placeholder="Aller vers…" aria-label="Filtrer les destinations"/><button aria-label="Fermer" onClick={close}><X size={17}/></button></header><div>{filtered.length?filtered.map(([id,label,key])=><button key={id} onClick={()=>go(id)}><span>{label}</span><kbd>{key}</kbd></button>):<p className="command-empty">Aucune destination trouvée</p>}</div></motion.div></motion.div>}
